#
#
#
version: 2
jobs:
  build:
    docker:
      - image: grafana/grafana-oss-ci-msi-build
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create OSS MSI
          command: |
            oss/ci-wrapper.sh 5.4.3
